### ISSUE TITLE
[객체지향의 사실과 오해] 1주차 - 협력하는 객체들의 공동체

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#1]
객체지향의 사실과 오해, 1장 협력하는 객체들의 공동체를 읽은 후:
- 정리한 글
- 코드
- etc

**Comment by joowankim** [comment]
글: https://www.notion.so/8d73ae05b48d4ec9bf9002b1abae7f60
코드: https://github.com/joowankim/cafe-order-system

**Comment by parksjin01** [comment]
#   역할 + 책임 + 협력
### 역할
- 여러 객체가 동일 역할 수행 가능
- 다른 객체가 역할 대체 가능
- 역할을 수행하는 방법은 자율적
- 하나의 객체가 여러 역할을 수행 가능

### 객체는 상태와 행동을 가짐.
- 행동과 상태가 분리된 객체는 좋지 못한 디자인일까?
- e.g. 상태를 저장하기 위해서만 사용되는 객체와, 상태를 저장하는 객체를 생성하기만 하는 객체
- e.g. 스프링 MVC의 빈들

**클래스가 객체지향 프로그래밍에서 중요한 요소이기는 하지만, 객체지향 프로그래밍의 중심에는 객체가 존재해야한다.
훌륭한 객체지향 프로그램을 설계하기 위해서는 클래스 관점에서 객체의 관점으로 사고 전환이 중요!!**

코드: https://github.com/parksjin01/OOP/tree/main/src/main/kotlin/chapter01

**Comment by snaag** [comment]
# 1. 협력하는 객체들의 공동체

## 1. 객체란?

객체란 상태와 행동에 따라 **무언가를 하는 것** 을 말한다. 상태란 행동을 하는 데에 필요한 것을 말한다.

예를 들어, **카페** 라면 **바리스타** 는 주문이 들어오면 알고 있는 레시피에 따라 만들 수 있어야 하고, **캐셔** 는 주문을 받는 방법에 따라 주문을 받을. 수 있어야 한다. **손님** 은 주문을 하는 방법에 따라 주문을 할 수 있어야 한다.

하지만 **객체가 되기 위해 만족시켜야 할 것** 이 있다.

## 2. 객체가 되기 위한 조건

카페에서 커피를 주문을 하고 받는 일련의 과정을 하나의 목표로 본다면, 손님은 캐셔에게 원하는 메뉴를 올바르게 주문하고 적절한 금액을 내야 한다. 캐셔는 손님이 주문한 메뉴와 금액을 잘 확인하고, 이를 바리스타에게 잘 전달해야 한다. 바리스타는 캐셔로부터 받은 주문에 맞는 레시피에 따라 올바른 음료를 만들어야 한다. 그리고 음료가 다 만들어지면 손님에게 잘 전달해야 한다.

만약 여기서 손님이 올바르게 주문을 하지 않고, 캐셔가 바리스타를 싫어해서 메뉴를 잘 전달하지 않았으며, 바리스타가 기분이 나빠서 올바르게 만들지도 않고 손님에게 제대로 전달하지 않는다면 이 목표는 실패한 것이다. 왜냐하면 각자가 모두 자신의 일을 잘 수행하지 않았으며 다른 사람들과 제대로 협력하지도 않았기 때문이다.

즉, 사람들을 객체로 바꿔본다면, _객체란 자신의 **역할** 에 **책임** 을 갖고, 자신을 필요로하는 다른 객체, 혹은 자신이 도움이 필요한 다른 객체와 적극적으로 **협력** 을 하는 것_ 을 말한다. 그리고 이를 통해 자신이 해결해야 하는 (작은) 문제들을 잘 해결하고, 더 나아가 다른 객체들과. 협업을 통해 더 큰 문제를 잘 해결할 수 있어야 한다.

## 3. 객체 지향이란

객체지향이라는 말을 들었을 때, 일반적으로 클래스라는 단어에 집중하게 된다. 하지만 이러한 생각은 **객체 지향과 더욱 멀어지게 된다.** 왜냐하면 **객체 지향이란 (협력하는) 객체를 지향하는 것** 이기 때문이다.

따라서 클래스에 집중하기 보다, 협력하는 객체의 관점에서 **객체들이 어떻게 협력하는지** 가 더 중요하다. 클래스는 협력 관계를 코드로 옮기는 도구일 뿐이다.

> 코드를 담는 클래스의 관점에서 메시지를 주고받는 객체의 관점으로 사고의 중심을 전환해야 한다.

## 📟 코드 및 실행 화면

-   [코드와 함께 보기](https://stackblitz.com/edit/oop-01?file=index.js)

-   [실행 화면만 보기](https://oop-01.stackblitz.io)

> 1초 뒤에 오픈하고, 1.5초 뒤에 주문한 음료가 완료됨
