### ISSUE TITLE
[객체지향의 사실과 오해] 2주차 - 이상한 나라의 객체

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#2]

**Comment by joowankim** [comment]
글: https://www.notion.so/9ead9385914f4a1b8886d04789c5fbb7
코드: https://github.com/joowankim/cafe-order-system
.

**Comment by parksjin01** [comment]
- 객체의 상태는 행동에 의해서만 달라진다.
- 행동의 결과는 이전 상태에 따라 달라진다. 
- 객체의 행동만 외부에 노출되어야 하며, 객체의 상태는 외부로 노출되어서는 안된다. (캡슐화)
    - 캡슐화가 잘 되어야지만 객체의 자율성이 높아지고, 변경에도 좀더 자유로워 진다.
- 객체를 만들 때는 먼저 어떤 협력과정에 객체가 참여하는지 파악하고, 그에 따라서 필요한 행동을 결정한다음 행동을 위해 필요한 상태를 정해야한다.
    - 상태를 먼저 결정했을 때 문제점
        - 캡슐화 저해 (?)
        - 다른 객체와의 협력 저해 (?)
        - 재사용성 저해 (?)

코드: https://github.com/parksjin01/OOP/blob/main/src/main/kotlin/chapter02/CoffeeScenario.kt
(기존코드에서 AccountBook, AccountBook2 라는 객체만 추가함)
