### ISSUE TITLE
[객체지향의 사실과 오해] 3주차 - 타입과 추상화 & 역할, 책임, 협력

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#3]
.

**Comment by joowankim** [comment]
### [타입과 추상화](https://www.notion.so/f28ad383d2764d938c9e46560a3725c5)

- 객체를 분류하는 기준은 언제나 **객체의 행동**이다.
- 객체를 분류하기 위한 **개념**을 프로그래밍에서는 **타입**이라고 부른다.
- **같은 행동**을 하는 서로 다른 객체는 **같은 타입**으로 분류될 수 있다.
- '다른 타입'에 정의된 행동을 모두 할 수 있으며 좀 더 특수한 행동까지도 행할 수 있다면 **그 타입**은 '다른 타입'의 **서브 타입**이다. 또한 '**다른 타입**'은 그 서브 타입의 **수퍼 타입**이다.
- 서브 타입은 슈퍼 타입을 대체할 수 있다. (서브 타입은 슈퍼 타입의 모든 행동을 행할 수 있으니까)
- 타입은 시간에 따라 동적으로 변하는 객체의 복잡성을 배제할 수 있게 해준다.
- 동적 모델 - 런타임, 정적 모델 - 컴파일 타임

### [역할, 책임, 협력](https://www.notion.so/c64daa039867403db97da90c2c072850)

- 한 객체가 다른 객체로 부터 어떤 요청을 받을 때, 요청을 받는 객체는 그 **요청에 대한 책임**이 있음을 의미한다.
- 한 객체가 처리할 수 있는 요청을 또 다른 객체가 처리할 수 있다면 이 두 객체는 같은 **역할**을 갖는다고 말할 수 있다. → 두 객체는 같은 책임을 갖는다.
- **객체나 역할**들에 **책임을 할당**하여 **협력**을 할 수 있도록 한다.
- 객체지향 설계 기법은 **책임-주도 설계**을 기반으로 한다.

**Comment by parksjin01** [comment]
## 타입과 추상화
- 추상화를 통해서 객체들의 복잡성을 단순화함
- 추상화: 일반화 -> 불필요한 세부사항을 제거
- 클래스는 프로그래머가 타입을 구현화할 수 있도록 언어가 제공하는 기능
- 메모리의 데이터는 1, 0 비트로만 존재하지만 데이터 타입을 통해서 해당 데이터가 수행할 수 있는 행동을 알 수 있듯, 객체의 타입도 타입(클래스)를 보고 내부 데이터가 어떻게 저장될지는 알 수 없어도 타입을 보고 해당 객체가 수행할 수 있는 행동을 알 수 있어야한다.
     - 객체의 타입에 따라 결정되는 것은 상태가 아니라 행동
     - 객체에 타입의 타입을 결정할 때 생각해야하는 것은 행동!
     - 객체의 타입을 보고 내부 데이터를 알 수 있으면 안된다 -> 캡슐화
- 일반화/특수화 관계
  - A 타입이 B 타입이 할 수 있는 행동을 모두 할 수 있고 추가 행동을 더 할 수 있는 경우 A와 B 타입 사이에는 일반화/특수화 관계가 성립한다.
  - 일반화/특수화 관계 == 상위타입 / 하위타입
  - 상위타입은 하위타입보다 할 수 있는 행동이 적음, 하위타입은 상위타입이 할 수 있는 행동을 모두 할 수 있고 추가로 더 많은 행동을 할 수 있음
  - 하위타입은 상위타입이 하는 행동을 모두 할 수 있기 때문에 상위타입을 대체할 수 있음 -> LSP
- 동적 모델 = 런타임 = 객체 / 정적 모델 = 컴파일 타임 = 클래스

## 역할, 책임, 협력
- 하나의 목적을 이루기 위해 여러 객체가 서로 협력한다.
- 협력 과정에서 객체가 다른 객체들에게 해줄 수 있는 행동을 책임이라고 부른다
 - **객체지향 프로그래밍에서 가장 중요한 부분은 책임을 적절한 객체에게 할당하는것**
- 다른 객체의 책임을 수행하도록 요청하는 과정을 메시지 전송이라 부른다. 메시지를 수신하는 객체는 메시지에 대해 적절한 책임을 수행해야 한다.
- 역할을 사용하면 협력 과정을 추상화 할 수 있다. 
  - 협력에 구체적인 객체를 지정하게 되면, 동일한 책임을 갖는 다른 객체가 협력에 참여했을 때 새로운 협력으로 처리해야한다.
  - 객체가 많다면 다뤄야하는 협력이 많아진다.
  - 역할이란 협력에서 특정 객체를 지정하지 않고 협력에 참여하기 위해 필요한 책임을 정의한 placeholder 같은것
  - 협력을 정의할 때 역할을 사용하면, 해당 역할을 수행할 수 있는 객체들은 누구나 협력 과정에 참여할 수 있다.
- 객체지향 프로그래밍을 설계할 때는 협력을 먼저 정의하고, 협력에 필요한 책임을 객체에 할당한 다음 객체가 해당 책임을 수행하기 위해 필요한 상태를 정의해야한다.

코드: https://github.com/parksjin01/OOP/tree/main/src/main/kotlin/chapter04
