### ISSUE TITLE
[객체지향의 사실과 오해] 4주차 - 책임과 메시지 & 객체 지도

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#4]

**Comment by joowankim** [comment]
[책임과 메시지](https://www.notion.so/3c07aed336aa45439e1aa64866ff6328)

- 객체는 메시지를 주고 받으며 협력한다.
- 메시지로 무엇을 해야하는 지 정의하고 누가 메시지를 받을지 생각한다.
- 메시지를 전송받을 수 있는 공용 인터페이스를 최소화하여 객체를 캡슐화하자.
- 적절하게 추상화된 메시지로 같은 책임에 대해 서로다른 처리방법을 사용할 수 있도록 다형성을 활용하자.

[객체 지도](https://www.notion.so/0ce94f46fe0b400e90a74b321e85b5ef)

- **도메인 모델**이란 사용자가 프로그램을 사용하는 대상 **영역에 관한 지식**을 선택적으로 **단순화**하고 의식적으로 **구조화**한 형태다.
- **유스케이스**는사용자의 목표를 달성하기 위해 **사용자와 시스템 간**에 이뤄지는 **상호작용의 흐름을 텍스트로 정리한 것**이다.
- 도메인 모델을 이용해 안정적인 소프트웨어 구조를 설계할 수 있다.
- 유스케이스에서 소프트웨어에 요구되는 기능을 알아내어 소프트웨어에 책임을 부여할 수 있다.
- 소프트웨어에 부여된 책임은 도메인 모델의 개념으로 만들어진 소프트웨어 내의 객체들에 세분화되어 할당된다.

코드: https://github.com/joowankim/cafe-order-system

**Comment by parksjin01** [comment]
### 책임과 메시지

- 메시지는 객체간 협력을 할 수 있는 수단
- 메시지는 추상적이여야 하지만 충분히 구체적이여야 한다. 
  - 메시지가 구체적일수록 메시지를 수신하는 객체의 자유도는 떨어진다.
  - 메시지가 너무 추상적이면 메시지를 수신해서 어떤 일을 해야할 지 알 수 없다.
  - 메시지를 정의할 때는 **어떻게**가 아닌 **무엇을**에 집중해야 한다. (What / Who 사이클)
- 메시지 이름과 argument를 합쳐서 메시지라고 부른다.
- 자바의 경우 메시지 수신 객체를 메시지 앞에 작성해서 메시지를 송신할 수 있다.
- 객체가 메시지를 수신했을 때 메시지 처리를 위한 행동을 정의한 것을 메소드라고 할 수 있다.
  - 메시지 전송과 메소드가 분리되어 있기 때문에 송신자와 수신자간 연결이 약해진다.
- 코드: https://github.com/parksjin01/OOP/tree/main/src/main/kotlin/chapter05

### 객체 지도
- 사용자의 요구사항은 계속해서 변하기 때문에 코드는 계속해서 변경이 필요하다.
- 미래에 일어날 변경을 미리 예측해서 코드를 작성하는 것은 불가능하다.
  - 미래 변경을 예측하지 말고 변경을 좀더 쉽게 수용할 수 있도록 -> 변경에 따른 영향이 최소화되도록 코드를 짜자
- 프로그램: 사용자에게 제공되는 기능 + 프로그램 구조
- 프로그램의 구조(객체간 관계)를 기반으로 코드를 작성해야 변경에 좀더 유연하게 대응할 수 있는 코드를 짤 수 있다.
- 도메인에 사용되는 개념간 관계를 표현하는 도메인 모델을 사용하면 객체간 관계 구조를 그리는데 도움이 된다.
- 유스케이스를 정리해보면 프로그램이 사용자에게 제공해야할 기능을 파악할 수 있다.
- 도메인 모델을 바탕으로 초기 객체를 정의하고 유스케이스를 통해 파악한 기능을 제공하기 위한 책임을 객체에 할당해나가면 변경에 유연하게 대응할 수 있고, 이해하기도 쉬운 코드를 작성할 수 있다.
