### ISSUE TITLE
[TDD] 1주차 - 오픈소스 분석 및 알고리즘 문제 풀이 구현

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#5]
오픈소스 분석 - Spring Batch
1. getting started 해보기
2. Spring Batch meta db 살펴보기

알고리즘 문제 풀이 구현 및 설명
https://www.acmicpc.net/problem/15685

**Comment by parksjin01** [comment]
스프링 배치 ERD
- 스프링 배치를 사용하는 프로젝트는 다음주에 진행할께요 ㅠㅠㅠ
![ERD](https://raw.githubusercontent.com/parksjin01/parksjin01/main/spring_batch_erd.svg)

알고리즘 문제
- https://github.com/parksjin01/kotlin-program-solving/tree/master/src/main/kotlin/p15685

**Comment by joowankim** [comment]
스프링 배치 - getting started manually
https://github.com/joowankim/start-spring-batch

알고리즘
https://github.com/joowankim/TDD_with_algorithm_problems/tree/master/problems/dragonCurve
