### ISSUE TITLE
[TDD] 2주차 - Spring Batch  분석 및 알고리즘 문제풀이

### ISSUE THREAD

**Issue by joowankim** [3tudy/OOP-study#6]
### 알고리즘 문제 풀이 구현 및 설명
https://www.acmicpc.net/problem/1966

**Comment by parksjin01** [comment]
알고리즘 문제 풀이: https://github.com/parksjin01/kotlin-program-solving/tree/master/src/main/kotlin/p1966

**Comment by joowankim** [comment]
알고리즘 문제풀이: https://github.com/joowankim/TDD_with_algorithm_problems/tree/master/problems/printerQueue
